spring.application.name=tour-de-jug

spring.datasource.url=jdbc:postgresql://localhost:5432/tourdegjug
spring.datasource.username=tourdegjug
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:change-me}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:change-me}
